### PR TITLE
Add conda setup to readme

### PR DESCRIPTION
**Pull request by AndersSpringborg**
I've added the a method for setting up a conda environment, as I had problems with spacy on windows. This worked for me, when i could't install spacy in a venv(VirtuelEnvirorment)

### CODE REVIEW

**Review by kaareHH — APPROVED** [review]
Looks nice

**Comment by madsthom** [comment]
Måske vi også skulle skrive hvordan man sætter environment op med virtualenv?

**Review by mkakbas — APPROVED** [review]

**Review by KasperSWinkler — APPROVED** [review]

**Review by madsthom — APPROVED** [review]
Now i guess its fine

**Review by KasperSWinkler — COMMENTED** [review]
Hej

Kan ikke se Pip install -r

Skal vi ikke have den med?

**Pull request merged**
